### ISSUE TITLE
Search command not working anymore

### ISSUE THREAD

**Issue by brodokk** [NeosVR-Community-Projects/accesslistmanager#3]
```
accesslistbot_1  | Traceback (most recent call last):
accesslistbot_1  |   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1353, in process_application_commands
accesslistbot_1  |     await app_command.invoke(interaction)
accesslistbot_1  |   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 724, in invoke
accesslistbot_1  |     await self.invoke_children(inter)
accesslistbot_1  |   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 713, in invoke_children
accesslistbot_1  |     await subcmd.invoke(inter, **kwargs)
accesslistbot_1  |   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 364, in invoke
accesslistbot_1  |     raise CommandInvokeError(exc) from exc
accesslistbot_1  | disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'verifier_discord_username' referenced before assignment
```

**Comment by brodokk** [comment]
Note: it's working after a restart it seems but still doesn't count as a fix

**Comment by brodokk** [comment]
Fixed in resonite commits support
